default: amde.l9bi.d.202c.prxt3

amdl.l9bi.d.202c: famdl.l9bi.d.202c
	form-amdl.d 2 famdl.l9bi.d.202c amdl.l9bi.d.202c

amdl.l9bi.d.202c.prxt3: amdl.l9bi.d.202c
	redistrb.cy.d redistrb.sun.prxt3.in > ttt.red.sun.out

amde.l9bi.d.202c.prxt3: adipls.sun.in amdl.l9bi.d.202c.prxt3
	adipls.c.d adipls.sun.in > ttt.adi.sun.out
